FROM python:latest
RUN mkdir -p /Data
COPY BCSC_DataSet_WebScraping_Uploadig.py / 
COPY /Data /Data
COPY config.json /
RUN pip install AzureML
RUN pip install lxml
RUN pip install Mechanicalsoup
RUN pip install Azure

CMD ["python","BCSC_DataSet_WebScraping_Uploadig.py"]